### PR TITLE
[SU-641] Add organisation pages to frontend performance tests

### PR DESCRIPTION
**Pull request by R-cen**
Organisation pages require the role ID as part of the URLs so we have added additional consul keys with the role IDs of the users that we are using the run the tests in each environment/region.

Example build running here with the changes https://buildkite.com/safetyculture/run-frontend-performance-tests/builds/528#72a30c61-a8a5-471e-89ec-ac2b7fcbf0a7

### CODE REVIEW

**Review by jponc — APPROVED** [review]
💯

**Comment by R-cen** [comment]
Test comment adding via API

**Comment by R-cen** [comment]
Frontend Performance Tests has completed. See results on the [dashboard](https://grafana.cmh.internal.safetyculture.com/d/CuRAoGbGz/frontend-performance-tests-dashboard)

**Comment by R-cen** [comment]
Frontend Performance Tests has completed. See results on the [dashboard](https://grafana.cmh.internal.safetyculture.com/d/CuRAoGbGz/frontend-performance-tests-dashboard)

**Comment by R-cen** [comment]
Frontend Performance Tests has completed. See results on the [dashboard](https://grafana.cmh.internal.safetyculture.com/d/CuRAoGbGz/frontend-performance-tests-dashboard) :smile:

**Comment by R-cen** [comment]
Frontend Performance Tests has completed. See results on the [dashboard](https://grafana.cmh.internal.safetyculture.com/d/CuRAoGbGz/frontend-performance-tests-dashboard) :lighthouse:

**Comment by R-cen** [comment]
:rotating_light: :rotating_light: :rotating_light: Frontend Performance Tests completed with changes from this PR :rotating_light: :rotating_light: :rotating_light: 
 See results on the [dashboard](https://grafana.cmh.internal.safetyculture.com/d/CuRAoGbGz/frontend-performance-tests-dashboard) :chart_with_upwards_trend: :chart_with_downwards_trend: :rocket:

**Pull request merged**
